Iter13
msmkdenis/yap-shortener pull request #13
Opened 2023-11-10 14:02 UTC by msmkdenis

2023-11-15 20:19 UTC, vovean requested changes

2023-11-15 20:19 UTC, vovean commented on internal/app/app.go
> +		repository = db.NewPostgresURLRepository(postgresPool, logger)
каждый из этих методов по-хорошему должен отдавать ошибку, а ты ее обрабатывать, и фаталить вот здесь. Лучше фаталить в одном месте, чем в куче других, так будет проще отследить + ты избавишься от побочных эффектов (фатал) во многих методах, оставив его только в одном методе

2023-11-15 20:19 UTC, vovean commented on internal/config/config.go
>  }
для таких штук лучше использовать enum, через iota

почитай про enums in golang

2023-11-15 20:19 UTC, vovean commented on internal/config/config.go
> +func (c *Config) newStorageType() *RepositoryType {
вот этот метод должен бы возвращать енум типа репозитория

2023-11-15 20:19 UTC, vovean commented on internal/handlers/url_handler.go
> +	if err := h.checkRequest(string(body)); err != nil {
ты там проверяешь, что строка пустая, но если она пустая, то ты свалишься еще выше, на анмаршалинге из json. Так что здесь проверять пустую строку нет смысла. А вот проверить длину urlBatchRequest на 0 можно

2023-11-15 20:19 UTC, vovean commented on internal/handlers/url_handler.go
> +		h.logger.Error("StatusConflict: url already exists", zap.Error(fmt.Errorf("caller: %s %w", utils.Caller(), err)))
тут скорее warn, потому это - часть нормальной бизнес-логики, никакой непредвиденной или неисправимой для дальнейшей работы ситуации

2023-11-15 20:19 UTC, vovean commented on internal/handlers/url_handler.go
> +		h.logger.Error("StatusConflict: url already exists", zap.Error(fmt.Errorf("caller: %s %w", utils.Caller(), err)))
тут тоже варн

2023-11-15 20:19 UTC, vovean commented on internal/handlers/url_handler_test.go
> +			_ = h.FindURL(l)
а ошибку проверить? Если она есть, то тест явно  зафейлить надо

2023-11-15 20:19 UTC, vovean commented on internal/handlers/url_handler_test.go
> +			_ = h.FindURL(l)
привет, я ошибка, проверь меня полностью

2023-11-15 20:19 UTC, vovean commented on internal/model/url.go
> +	Ping(c echo.Context) error
будь аккуратнее, добавляя новые методы в интерфейс - как бы не нарушить I из SOLID - interface segregation. Ping еще выглядит не так плохо, потому что его не так сложно реализоваться для того же inmemory репозитория, но с какими-то более специфичными методами такое может уже не прокатить

Тут уже тоже не идеально получается, если что

2023-11-15 20:19 UTC, vovean commented on internal/repository/db/db_url_repository.go
> +	//"strings"
удали

2023-11-15 20:19 UTC, vovean commented on internal/repository/db/db_url_repository.go
> +func (r *PostgresURLRepository) Ping(ctx echo.Context) error {
вот это уже не очень хорошо, что что ты передаешь в репозиторий какую-то сущность аж из транспорта (т е еще и через сервис протащил), а именно echoo.Context.

Оно, может и называется контекстом, но совсем не тот контекст, который мы передаем в гошке. Если ты хочешь использовать контекст оттуда (а ты хочешь и это правильно), то нужно достать его как можно раньше и дальше использовать его. На уровне транспорта достаешь ctx.Request().Context() и дальше работаешь только с ним

2023-11-15 20:19 UTC, vovean commented on internal/repository/db/db_url_repository.go
> +		returning id, original_url, short_url
такие запросы тоже можно в sql файлы вытащить и эмбеддить

2023-11-15 20:19 UTC, vovean commented on internal/repository/db/db_url_repository.go
> +	re, err := regexp.Compile(`\d|-`) // mustcompile throws panic instead of error
есть функция MustCompile

2023-11-15 20:19 UTC, vovean commented on internal/repository/db/postgres.go
> +	if err == nil {
а если != nil не будешь обрабатывать? т е у тебя создастся нерабочий пул коннекто и все, бай бай

2023-11-15 20:19 UTC, vovean commented on internal/repository/file/file_url_repository.go
> +	var urlMap = make(map[string]model.URL)
сразу выделить память

2023-11-15 20:19 UTC, vovean commented on internal/repository/file/file_url_repository.go
> +		if err == io.EOF {
ошибки лучше проверять через errors.Is

2023-11-15 20:19 UTC, vovean commented on internal/repository/file/file_url_repository.go
> +	if len(urlMap) > 0 {
не обязательно проверять на длину, можно сразу запустить for

если мапа пустая, то просто цикл сразу же и закончится

2023-11-15 20:19 UTC, vovean commented on internal/repository/file/file_url_repository.go
> +	var urlMapIn = make(map[string]model.URL)
выделить память

2023-11-15 20:19 UTC, vovean commented on internal/service/url_service.go
> +	for _, v := range urls {
тут тоже можно сразу память выделить

2023-11-15 20:19 UTC, vovean commented on internal/service/url_service.go
> +	fmt.Println(urlsToSave)
принт это бан

2023-11-15 20:19 UTC, vovean commented on internal/service/url_service.go
> +	fmt.Println(savedURLs)
нельзя принты в продакшн коде держать

2023-11-17 07:27 UTC, msmkdenis commented on internal/app/app.go
> +		repository = db.NewPostgresURLRepository(postgresPool, logger)
Вынес логику в метод initRepository, перенёс в него все фатал логи.

2023-11-17 07:27 UTC, msmkdenis commented on internal/config/config.go
>  }
Переделал на enum

2023-11-17 07:28 UTC, msmkdenis commented on internal/config/config.go
> +func (c *Config) newStorageType() *RepositoryType {
Переделал на enum

2023-11-17 07:32 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +	if err := h.checkRequest(string(body)); err != nil {
Добавил проверку на пустой batch request

2023-11-17 07:32 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +		h.logger.Error("StatusConflict: url already exists", zap.Error(fmt.Errorf("caller: %s %w", utils.Caller(), err)))
Заменил на warn

2023-11-17 07:33 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +		h.logger.Error("StatusConflict: url already exists", zap.Error(fmt.Errorf("caller: %s %w", utils.Caller(), err)))
Заменил на warn

2023-11-17 07:33 UTC, msmkdenis commented on internal/handlers/url_handler_test.go
> +			_ = h.FindURL(l)
добавил проверку на отсутствие ошибки

2023-11-17 07:33 UTC, msmkdenis commented on internal/handlers/url_handler_test.go
> +			_ = h.FindURL(l)
добавил проверку на отсутствие ошибки

2023-11-17 07:35 UTC, msmkdenis commented on internal/model/url.go
> +	Ping(c echo.Context) error
Пока оставил так, изучаю вопрос, как организовывать код в таких случаях.

2023-11-17 07:35 UTC, msmkdenis commented on internal/repository/db/db_url_repository.go
> +	//"strings"
Удалил))

2023-11-17 07:38 UTC, msmkdenis commented on internal/repository/db/db_url_repository.go
> +func (r *PostgresURLRepository) Ping(ctx echo.Context) error {
Упоминал вопрос на созвоне, т.к. да эхо контекст это другой контекст ) Тоже смутился в какой-то момент, что пробросил вовнутрь не тот контекст.
Заменил везде на обычный контекст.

2023-11-17 07:39 UTC, msmkdenis commented on internal/repository/db/db_url_repository.go
> +	re, err := regexp.Compile(`\d|-`) // mustcompile throws panic instead of error
Изначально не использовал mustcompile, т.к. он может бросать панику. С другой стороны мы абсолютно уверены в типе строки, т.к. генерируется через uuid.
Заменил.

2023-11-17 07:42 UTC, msmkdenis commented on internal/repository/db/postgres.go
> +	if err == nil {
Точно, переделал на возврат ошибки.

2023-11-17 07:47 UTC, msmkdenis commented on internal/repository/file/file_url_repository.go
> +	var urlMap = make(map[string]model.URL)
Скорректировал

2023-11-17 07:48 UTC, msmkdenis commented on internal/repository/file/file_url_repository.go
> +		if err == io.EOF {
Переделал проверку

2023-11-17 07:49 UTC, msmkdenis commented on internal/repository/file/file_url_repository.go
> +	if len(urlMap) > 0 {
Скорректировал

2023-11-17 07:50 UTC, msmkdenis commented on internal/repository/file/file_url_repository.go
> +	var urlMapIn = make(map[string]model.URL)
Скорректировал

2023-11-17 07:51 UTC, msmkdenis commented on internal/service/url_service.go
> +	for _, v := range urls {
done

2023-11-17 07:51 UTC, msmkdenis commented on internal/service/url_service.go
> +	fmt.Println(urlsToSave)
удалил)

2023-11-17 07:51 UTC, msmkdenis commented on internal/service/url_service.go
> +	fmt.Println(savedURLs)
Тоже удалил)

2023-11-17 08:06 UTC, msmkdenis commented on internal/repository/db/db_url_repository.go
> +		returning id, original_url, short_url
убрал запросы в файлы

2023-11-21 19:04 UTC, vovean approved these changes

2023-11-22 07:59 UTC, merged