Iter15
msmkdenis/yap-shortener pull request #15
Opened 2023-11-22 12:25 UTC by msmkdenis

2023-11-28 20:56 UTC, vovean requested changes

2023-11-28 20:56 UTC, vovean commented on internal/app/app.go
> +			e.Logger.Fatal("shutting down the server")
fatal тут не лучший вариант, потому что, судя по коду ниже ты пытаешься сделать graceful shutdown, который fatal явно никак не соблюдает.

К тому же, что если у тебя появится второй компонент, которые тоже может так завершиться. Если его фаталить, то graceful shutdown для http сервера не будет работать

2023-11-28 20:56 UTC, vovean commented on internal/app/app.go
> +func initRepository(cfg *config.Config, logger *zap.Logger) service.URLRepository {
принимай интерфейсы (не так критично), **возвращай структуры**?

2023-11-28 20:56 UTC, vovean commented on internal/handlers/dto/url_dto.go
> -type URLResponseType struct {
эм, а зачем в названии нового типа писать слово Type? и так, вроде, понятно, что это тип, а не ... что-то другое

2023-11-28 20:56 UTC, vovean commented on internal/handlers/dto/url_dto.go
> +type URLBatchResponseByUserID struct {
а тут ты, почему-то, решил не писать слово Type в названии

2023-11-28 20:56 UTC, vovean commented on internal/utils/jwt_manager.go
> +		UserID: uuid.New().String(),
т е, если пользователь потеряет свою куки, то он больше никогда не сможет получить ссылки свои? Потому что в следующий раз ему сгенерится новый id'шник

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler.go
> +	userID := c.Get("userID").(string)
а проверить на ,ok?

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler.go
> +	workerPool := utils.NewWorkerPool(runtime.GOMAXPROCS(-1), h.logger)
у тебя тут io-задача, не cpu-задача, так что можно делать намного больше воркеров, чем у тебя есть ядер

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler.go
> +	workerPool.Stop()
может через defer?

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler.go
> +			err = h.urlService.DeleteAllByUserID(c.Request().Context(), c.Get("userID").(string), url)
приводить к string без проверки на ,ok чревато паникой

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler.go
>  		h.logger.Error("StatusBadRequest: unknown error", zap.Error(fmt.Errorf("caller: %s %w", utils.Caller(), err)))
вроде, zap и так выводить стактрейс ошибки при использовании zap.Error, так что не обязательно явно прописывать Caller

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler_test.go
> +	logger, _ := zap.NewProduction()
а ошибку проверить...

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler_test.go
> +	defer e.Close()
может перенести defer поближе к созданию самой переменной?

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler_test.go
>  	defer ctrl.Finish()
вот это нужно делать внутри каждого табличного теста (внутри t.Run()), потому что именно внутри .Finish() делаются все проверки (что было вызвано, с какими параметрами, сколько раз и т д). Если ты это делаешь только в самом конце, после всех табличных тестов, то у тебя все проверки разом прогонятся и будет непонятно, какой именно табличный тест сломан и еще я не уверен, как будут обработаны одинаковые моки, которые используются в разных методах.

Прочитай вот эту статью - https://habr.com/ru/companies/avito/articles/658907/

В разделе "Пишем табличные тесты" там про это как раз написано и показан код, как надо делать

2023-11-28 20:56 UTC, vovean commented on internal/handlers/url_handler_test.go
> +	s.EXPECT().GetAllByUserID(gomock.Any(), gomock.Any()).Return(nil, apperrors.ErrURLNotFound)
вот это тоже неправильное использование gomock. В рамках каждого табличного теста ты должен создавать новый контроллер, создавать новые моки со своими ожиданиями (EXPECT) и в конце каждрый раз проверять (делать ctrl.Finish())

2023-11-28 20:56 UTC, vovean commented on internal/middleware/jwt_token.go
> +			cookie, er := c.Request().Cookie(j.jwtManager.TokenName)
err

2023-11-28 20:56 UTC, vovean commented on internal/middleware/jwt_token.go
> +				newUserID, err := j.jwtManager.GetUserID(token)
по-хорошему в такой ситуации нужно кидать пользака на авторизацию и оттуда доставать user_id, из базы

генерить рандомно - хмхм

2023-11-28 20:56 UTC, vovean commented on internal/middleware/jwt_token.go
> +				j.logger.Warn("token not found, creating new token", zap.Error(er))
сомневаюсь, что это варн, скорее инфо

потому что юзер не пытается делать ничего плохого, это - вполне нормальная ситуация в процессе работы с программой

2023-11-28 20:56 UTC, vovean commented on internal/repository/db/db_url_repository.go
> +	r.logger.Info("Deleting shortURLs", zap.Any("shortURLs", shortURLs))
вроде, был zap.Slice или zap.Strings

2023-11-28 20:56 UTC, vovean commented on internal/repository/db/db_url_repository.go
> +	result := tx.SendBatch(ctx, batch)
а ошибки тут никакой нет? Может внутри result?

2023-11-28 20:56 UTC, vovean commented on internal/repository/db/migration/000002_add_userid_to_url_table.up.sql
> +alter table url_shortener.url add column user_id text;
not null?

2023-11-28 20:56 UTC, vovean commented on internal/repository/db/queries/block_urls_by_userid_and_urlids.sql
> +select id, user_id, deleted_flag from url_shortener.url where user_id = $1 and id = any($2::text[]) for update
начиная с pgx v5 можно не делать ::text[], просто передаешь слайс гошный и счастье

2023-11-28 20:56 UTC, vovean commented on internal/repository/db/queries/create_tmp_table_like_url.sql
> +create temporary table %s (like url_shortener.url) on commit drop
выше видео это же выражение ты формируешь прям в коде. Файл лишний или там поменять забыл?

2023-11-28 20:56 UTC, vovean commented on internal/repository/file/file_url_repository.go
> +	return nil
не будешь реализовывать это?

2023-11-28 20:56 UTC, vovean commented on internal/repository/file/file_url_repository.go
> +		if errors.Is(err, io.EOF) {
отлично, что сам заметил такой момент)

2023-11-28 20:56 UTC, vovean commented on internal/utils/jwt_manager.go
> +	tokenName = "token"
кхм кхе кхе

может через флаги или енв переменные?

2023-11-29 05:37 UTC, msmkdenis commented on internal/handlers/url_handler_test.go
>  	defer ctrl.Finish()
Тесты мне вообще не нравились как были реализованы. Я их переделал с использованием suite.Suite и SetupTest.
Интересно, что я ctrl.Finish не добавлял намеренно, т.к. с го 1.14 если в контролер передавать *testing.T эти штуки там автоматически закрываются (из доки). Статью я читал - это перевод статьи от 2020 г. как понял, тогда 1.14 только вышла. Но  целом перенес экспекты в testrun и там специально закрываю. Тесты работают и с закрытием и без закрытия (попробую как нибудь проверить).
PS табличные тесты вроде и круто - но когда они ломаются отладка становится довольно болезненной) Пока переделал на более классический вариант - потом буду еще думать как переделать.

2023-11-29 05:40 UTC, msmkdenis commented on internal/handlers/url_handler_test.go
> +	s.EXPECT().GetAllByUserID(gomock.Any(), gomock.Any()).Return(nil, apperrors.ErrURLNotFound)
См. комментарий выше, тесты переписал полностью, буду дорабатывать. 
PS тесты писать мне нравится! Пока разбираюсь как еще упростить их написание (хочется достичь удобства уровня java-вских тест фреймворков - уже близко ))))

2023-11-29 05:42 UTC, msmkdenis commented on internal/handlers/dto/url_dto.go
> -type URLResponseType struct {
Поменял, это idea за меня написала (или codeium) - не уследил)))

2023-11-29 05:43 UTC, msmkdenis commented on internal/handlers/dto/url_dto.go
> +type URLBatchResponseByUserID struct {
Убрал эти Type - не к месту они.

2023-11-29 05:45 UTC, msmkdenis commented on internal/utils/jwt_manager.go
> +		UserID: uuid.New().String(),
Ну такое ТЗ. В тз не предусмотрена идентификация, соответственно нет возможности каким-то образом понять по новому пользователю - какие у него были ID. Поэтому да - ответственность пользователя - потерял токен, получи новый, свои ссылки больше не увидишь. Других способов по тз нет.

2023-11-29 05:46 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +	userID := c.Get("userID").(string)
Я тут сознательно не проверял, т.к. все проверки делал в middleware, и там уже 100% рабочий userID цеплял к контексту. Не знаю возможна ли тут ошибка?

2023-11-29 05:47 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +	workerPool := utils.NewWorkerPool(runtime.GOMAXPROCS(-1), h.logger)
Согласен

2023-11-29 05:48 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +	workerPool.Stop()
Скорректировал

2023-11-29 05:49 UTC, msmkdenis commented on internal/handlers/url_handler.go
> +			err = h.urlService.DeleteAllByUserID(c.Request().Context(), c.Get("userID").(string), url)
Технически тут наверное не должно быть ошибки, т.к. к контексту в middleware цепляется либо сгенерированный либо вытащенный из jwt айди после всех проверок.

2023-11-29 05:49 UTC, msmkdenis commented on internal/handlers/url_handler_test.go
> +	defer e.Close()
Тесты переделал

2023-11-29 05:52 UTC, msmkdenis commented on internal/middleware/jwt_token.go
> +			cookie, er := c.Request().Cookie(j.jwtManager.TokenName)
Остатки битвы с shadow линтером

2023-11-29 05:53 UTC, msmkdenis commented on internal/middleware/jwt_token.go
> +				newUserID, err := j.jwtManager.GetUserID(token)
Полностью согласен, но такое ТЗ. Идентификация и хранение инфо о пользователе по тз не предполагается.

2023-11-29 05:53 UTC, msmkdenis commented on internal/middleware/jwt_token.go
> +				j.logger.Warn("token not found, creating new token", zap.Error(er))
Скорректировал

2023-11-29 05:55 UTC, msmkdenis commented on internal/repository/db/db_url_repository.go
> +	result := tx.SendBatch(ctx, batch)
ну SendBatch возвращает интерфейс, ошибку не возвращает. Ошибка обрабатывается на уровне попытки закрытия result ниже
```
	result := tx.SendBatch(ctx, batch)

	err = result.Close()
	if err != nil {
		return apperrors.NewValueError("close failed", utils.Caller(), err)
	}
```

2023-11-29 05:57 UTC, msmkdenis commented on internal/repository/db/queries/create_tmp_table_like_url.sql
> +create temporary table %s (like url_shortener.url) on commit drop
Строку формирую в коде и подстановкой таблицы в sql код
`createTmpTableQuery := fmt.Sprintf(createTmpTableLikeURL, tempTable)`
Идея была полностью вынести sql код из кода приложения в файлы. Придумал только так)

2023-11-29 06:09 UTC, msmkdenis commented on internal/handlers/url_handler_test.go
> +	logger, _ := zap.NewProduction()
Добавил проверку

2023-11-29 12:49 UTC, msmkdenis commented on internal/utils/jwt_manager.go
> +	tokenName = "token"
Добавил флаг и переменную с дефолтными значениями на выбор. Автотесты ЯП ни в какую не пропускают .env файл, хотя все локально работает (

2023-11-29 14:47 UTC, msmkdenis commented on internal/repository/db/queries/block_urls_by_userid_and_urlids.sql
> +select id, user_id, deleted_flag from url_shortener.url where user_id = $1 and id = any($2::text[]) for update
скорректировал

2023-11-29 14:48 UTC, msmkdenis commented on internal/repository/file/file_url_repository.go
> +	return nil
в тз оно не надо  вроде бы

2023-11-29 15:14 UTC, msmkdenis commented on internal/app/app.go
> +			e.Logger.Fatal("shutting down the server")
Скорректировал

2023-11-29 15:15 UTC, msmkdenis commented on internal/app/app.go
> +func initRepository(cfg *config.Config, logger *zap.Logger) service.URLRepository {
Тут придумал только такой способ как из одной функции вернуть один условный репозиторий, структуры которых лежат в разных пакетах.

2023-11-30 05:48 UTC, msmkdenis commented on internal/handlers/url_handler.go
>  		h.logger.Error("StatusBadRequest: unknown error", zap.Error(fmt.Errorf("caller: %s %w", utils.Caller(), err)))
zap выводит стак трейс до места вызова, но мне нужен был полный стак трейс до точки генерации первоначальной ошибки, поэтому оборачивал все через caller

2023-12-06 16:44 UTC, vovean approved these changes

2023-12-06 16:59 UTC, merged