Iter25
msmkdenis/yap-shortener pull request #25
Opened 2024-03-06 09:03 UTC by msmkdenis

2024-03-07 20:47 UTC, capsulated requested changes
Логика кода, структура и функционал -  всё в порядке. А вот по неймингу немного запутался, когда читал, так как неправильно подумал о функционале тех объектов, которые названы соответствующим образом.

В принципе, ничего критичного в этом нет, но можно как-то переименовать. Если не согласен - пиши или можно договорится о 1-1. Календарик со следующей недели обновлю. Либо просто в директ в пачке.

Если со временем не очень - могу и заапрувить, так как ничего критичного, как уже написал, нет

2024-03-07 20:47 UTC, capsulated commented on integration_tests/url_handler_integration_test.go
> +	http2 "github.com/msmkdenis/yap-shortener/internal/api/http"
Плохой нейминг, не ясно, что именно это за пакет, тем более конфликтует со стандартным `http`. Это скорее `shortenerService`, или `shortenerHandling`, или `server`, или что-то похожее, что отражает функционал пакета

2024-03-07 20:47 UTC, capsulated commented on internal/api/grpc/url_handler.go
> +type URLHandler struct {
`URLHandler` очень сильно сбивает с толку, так как в gRPC, в отличии от REST, url'ы не используются. А если речь идёт о адресах для создания коротких ссылок, то тоже не совсем понятно, так как URL существует, как стандартный объект "net/url" (причём не только в го). Лучше их назвать как-то по-другому, к примеру `ShortenerService` или `UrlShortenerService`

2024-03-07 20:47 UTC, capsulated commented on internal/api/grpc/url_handler.go
> +type URLService interface {
Интерфейсы лучше называть с постфиксом `-er` по рекомендациям сообщества. Хотел спросить, зачем интерфейс тут в принципе, но увидел моки и useCase.

2024-03-07 20:47 UTC, capsulated commented on internal/api/grpc/url_handler.go
> +func NewURLHandler(service URLService, urlPrefix string, trustedSubnet string, jwtManager *jwtgen.JWTManager, logger *zap.Logger, wg *sync.WaitGroup) *URLHandler {
Повторюсь, очень сбивает с толку нейминг, скорее всего из-за URL. Я так понимаю, тут URL используется в контексе сокращения этих самых URL. Но в связке с Handler, кажется, что это хендлеры для каких то url дресов. Тут скорее хендлеры методов grpc: `grpcMethodHandlers` (это как пример)

2024-03-07 20:47 UTC, capsulated commented on internal/api/http/example_test.go
> +package http
Не не не не))) Не надо `http` называть)) `http` - это "net/http". Тут лучше server или ещё что-то подобное

2024-03-07 20:47 UTC, capsulated commented on internal/api/grpc/url_handler.go
> +type URLService interface {
И всё же лучше `ShortenerService` или ещё как-то, но точно не URL ))) `ShortUrlService` например или что-то подобное

2024-03-13 05:57 UTC, msmkdenis commented
Поменял нейминг, логика следующая:
в папке `api `есть пакеты: 

- `httphandlers `- для обработчиков запросов по `http`. 
- `grpchandlers `- для обработчиков запросов по `grpc`

Оставил их в виде "хэндлеров", т.к. в моей логике они обрабатывают запросы извне, а сервис - это что-то внутреннее.
Интерфейсы сервисов поменял на: `URLShortenerService`
Объекты хендлеров сделал единообразными: `URLShorten `и `NewURLShorten`, т.к. у них идентичный функционал по сути. При этом различаем мы их по пакетам. 
В app при создании объектов у нас соответственно:

- `grpchandlers.NewURLShorten(...)` - создаем обработчик по `grpc`
- `httphandlers.NewURLShorten(...)` - создаем обработчик по `http`

2024-03-13 17:56 UTC, capsulated approved these changes
Да всё супер, как и говорил, код в общем хорошо написан. Плюс, всё обговорили на 1-1.

Поздравляю с окончанием инкременов на курсе! И желаю успехов с выполнением выпускного проекта)

2024-03-14 04:19 UTC, merged